FROM python:3.9.1
RUN apt-get install wget
RUN pip install pandas sqlalchemy psycopg2 pyarrow fastparquet "numpy<2"


WORKDIR /app
COPY ingest_data_parquet.py ingest_data_parquet.py


ENTRYPOINT [ "python", "ingest_data_parquet.py" ]
