FROM prefecthq/prefect:2-latest
 
COPY requirements.txt .
RUN apt-get update && apt-get -y install wget libpq-dev gcc curl
RUN pip install -r requirements.txt --trusted-host pypi.python.org --no-cache-dir

COPY etl_gcs_to_bq_dockerized.py /opt/prefect/flows/etl_gcs_to_bq_dockerized.py
