services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  prefect:
    image: prefecthq/prefect
    ports:
      - "4201:4200"  # Expose the Prefect UI. Use port 4201 so that it doesn’t conflict with port 4200 that Prefect Portal is using
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_API_REQUEST_TIMEOUT=60
